### ISSUE TITLE
Add Swipe Refresh Layout 

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#71]
**Describe the feature you'd like**
In the MainFragment.kt when a profile becomes active it does not appears unless user navigates to other screen or reopen it again. To counter this problem add a swipe refresh layout so that there's no need for the user to navigate somewhere and come back.

**Screenshots**
<table>
        <tr>
<td><img src = "https://user-images.githubusercontent.com/61552810/99908341-175ea900-2d08-11eb-9a03-8c05cd22b927.gif" height = "480" width="250"></td>
<td><img src = "https://user-images.githubusercontent.com/61552810/99908347-247b9800-2d08-11eb-861f-963b2e6deff5.gif" height = "480" width="250"></td>
</tr>
</table>

**Would you like to work on the issue?**

- [x] Yes

**Comment by rob729** [comment]
IMO the Swipe to refresh approach is not good. As a developer, it should be our responsibility to show the latest data on the screen. That's why MVVM architecture with Livedata is being used so that the UI reacts to data changes.
You should think about how you can use the same to fix the Current active profile issue.

**Comment by coder2699** [comment]
@rob729 Yeah, I get your point. But right now I can't think of an optimal solution. If you feel adding swipe refresh layout is not good, then no problem.
