### ISSUE TITLE
Add an edit profile option

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#8]
**Describe the feature you'd like**
The user should be able to change the profile name, start & end time, and the days on which the profile has to be activated by using the edit option. 

**Additional context**
I would suggest to first work on issue #5 before working on this if it is not yet closed.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 how is the edit option expected, can we use a dialog box? Or we have to create a completely new editfragment and add it to navigation graph and all

**Comment by coder2699** [comment]
Or when the user selects edit, can we delete that profile and using newfragment only we allow the user to edit?

**Comment by rob729** [comment]
You have to show the edit option in the details fragment and when the user clicks on it you can take the user to NewProfileFragment, preload the data from the profile, and then let the user change the data. Don't delete the existing profile, just use update query in the room for database changes, and for work manager changes cancel the old one and create a new one.

**Comment by coder2699** [comment]
@rob729 My code is almost ready, working on Updating part. Just one thing I want to share, If we are using edit option from detailsFragment, app is not working efficiently. There is problem in preloading data and app crashes sometimes, also since it is bottom sheet, on navigation it was causing problem (i figured out a way, but it wasn't looking very good)

So I tried another method, when we use edit option from item_row, the app preloads perfectly from ProfileListAdapter and didn't crash even once, also the navigation is not causing any problem. Please check the image below, if you don't have any problems can I implement it this way?

<img src="https://user-images.githubusercontent.com/61552810/96923960-9bd2c780-14cf-11eb-9f9c-c14e454a6000.PNG" width="320px" height="240px"/>

**Comment by rob729** [comment]
@coder2699 No, UI wise this looks bad. 
You will have to figure out some way to do it from the details fragment itself.
Try using the navigation components, might help.

**Comment by coder2699** [comment]
@rob729 not even if I remove this icon, and if a user long presses any profile, edit option comes ? Otherwise I will try with details Frag....
